/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	apiv1alpha1 "github.com/Iceber/pod-running-control/api/v1alpha1"
	scheme "github.com/Iceber/pod-running-control/client-go/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// PodRunningGatesGetter has a method to return a PodRunningGateInterface.
// A group's client should implement this interface.
type PodRunningGatesGetter interface {
	PodRunningGates(namespace string) PodRunningGateInterface
}

// PodRunningGateInterface has methods to work with PodRunningGate resources.
type PodRunningGateInterface interface {
	Create(ctx context.Context, podRunningGate *apiv1alpha1.PodRunningGate, opts v1.CreateOptions) (*apiv1alpha1.PodRunningGate, error)
	Update(ctx context.Context, podRunningGate *apiv1alpha1.PodRunningGate, opts v1.UpdateOptions) (*apiv1alpha1.PodRunningGate, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*apiv1alpha1.PodRunningGate, error)
	List(ctx context.Context, opts v1.ListOptions) (*apiv1alpha1.PodRunningGateList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *apiv1alpha1.PodRunningGate, err error)
	PodRunningGateExpansion
}

// podRunningGates implements PodRunningGateInterface
type podRunningGates struct {
	*gentype.ClientWithList[*apiv1alpha1.PodRunningGate, *apiv1alpha1.PodRunningGateList]
}

// newPodRunningGates returns a PodRunningGates
func newPodRunningGates(c *PodRunningControlV1alpha1Client, namespace string) *podRunningGates {
	return &podRunningGates{
		gentype.NewClientWithList[*apiv1alpha1.PodRunningGate, *apiv1alpha1.PodRunningGateList](
			"podrunninggates",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *apiv1alpha1.PodRunningGate { return &apiv1alpha1.PodRunningGate{} },
			func() *apiv1alpha1.PodRunningGateList { return &apiv1alpha1.PodRunningGateList{} },
		),
	}
}
