/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	podrunningcontrolapiv1alpha1 "github.com/Iceber/pod-running-control/api/v1alpha1"
	versioned "github.com/Iceber/pod-running-control/client-go/clientset/versioned"
	internalinterfaces "github.com/Iceber/pod-running-control/client-go/informers/externalversions/internalinterfaces"
	apiv1alpha1 "github.com/Iceber/pod-running-control/client-go/listers/api/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// PodRunningGateInformer provides access to a shared informer and lister for
// PodRunningGates.
type PodRunningGateInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() apiv1alpha1.PodRunningGateLister
}

type podRunningGateInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewPodRunningGateInformer constructs a new informer for PodRunningGate type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewPodRunningGateInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredPodRunningGateInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredPodRunningGateInformer constructs a new informer for PodRunningGate type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredPodRunningGateInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.PodRunningControlV1alpha1().PodRunningGates(namespace).List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.PodRunningControlV1alpha1().PodRunningGates(namespace).Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.PodRunningControlV1alpha1().PodRunningGates(namespace).List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.PodRunningControlV1alpha1().PodRunningGates(namespace).Watch(ctx, options)
			},
		},
		&podrunningcontrolapiv1alpha1.PodRunningGate{},
		resyncPeriod,
		indexers,
	)
}

func (f *podRunningGateInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredPodRunningGateInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *podRunningGateInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&podrunningcontrolapiv1alpha1.PodRunningGate{}, f.defaultInformer)
}

func (f *podRunningGateInformer) Lister() apiv1alpha1.PodRunningGateLister {
	return apiv1alpha1.NewPodRunningGateLister(f.Informer().GetIndexer())
}
