/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/Iceber/pod-running-control/api/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// PodRunningGateLister helps list PodRunningGates.
// All objects returned here must be treated as read-only.
type PodRunningGateLister interface {
	// List lists all PodRunningGates in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apiv1alpha1.PodRunningGate, err error)
	// PodRunningGates returns an object that can list and get PodRunningGates.
	PodRunningGates(namespace string) PodRunningGateNamespaceLister
	PodRunningGateListerExpansion
}

// podRunningGateLister implements the PodRunningGateLister interface.
type podRunningGateLister struct {
	listers.ResourceIndexer[*apiv1alpha1.PodRunningGate]
}

// NewPodRunningGateLister returns a new PodRunningGateLister.
func NewPodRunningGateLister(indexer cache.Indexer) PodRunningGateLister {
	return &podRunningGateLister{listers.New[*apiv1alpha1.PodRunningGate](indexer, apiv1alpha1.Resource("podrunninggate"))}
}

// PodRunningGates returns an object that can list and get PodRunningGates.
func (s *podRunningGateLister) PodRunningGates(namespace string) PodRunningGateNamespaceLister {
	return podRunningGateNamespaceLister{listers.NewNamespaced[*apiv1alpha1.PodRunningGate](s.ResourceIndexer, namespace)}
}

// PodRunningGateNamespaceLister helps list and get PodRunningGates.
// All objects returned here must be treated as read-only.
type PodRunningGateNamespaceLister interface {
	// List lists all PodRunningGates in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apiv1alpha1.PodRunningGate, err error)
	// Get retrieves the PodRunningGate from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*apiv1alpha1.PodRunningGate, error)
	PodRunningGateNamespaceListerExpansion
}

// podRunningGateNamespaceLister implements the PodRunningGateNamespaceLister
// interface.
type podRunningGateNamespaceLister struct {
	listers.ResourceIndexer[*apiv1alpha1.PodRunningGate]
}
